Http/routes.php
<?php
/*
 |--------------------------------------------------------------------------
 |  R & D Group
 |--------------------------------------------------------------------------
*/
Route::group([
	'middleware' => config('researchdevelopment.middleware'),
	'prefix'     => config('researchdevelopment.prefix'),
	'namespace'  => 'Penta\ResearchDevelopment\Http\Controllers',
	'as'         => 'researchdevelopment.',
], function () {

	/*
	 |--------------------------------------------------------------------------
	 |  Development Group
	 |--------------------------------------------------------------------------
	*/
	Route::group(['prefix' => 'developments', 'as' => 'developments.'], function () {

		// Index
		Route::get('/', 'DevelopmentController@index')->name('index');
		// Data Table
		Route::get('/data', 'DevelopmentController@data')->name('data');
		// Store
		Route::post('/yeni-not', 'DevelopmentController@store')->name('store');
		// Show
		Route::post('/goster', 'DevelopmentController@show')->name('show');
		// Edit
		Route::get('/duzenle/{development}', 'DevelopmentController@edit')->name('edit');
		// Update Edit
		Route::put('/duzenle/{development}', 'DevelopmentController@updateEdit')->name('updateEdit');
		// Destroy
		Route::post('/sil/{id}', 'DevelopmentController@destroy')->name('destroy');

		// Show Pricing
		Route::get('/fiyat/{id}', 'DevelopmentController@showPricing')->name('showPricing');
		// Update Pricing
		Route::put('/fiyatlandir/{id}', 'DevelopmentController@updatePricing')->name('updatePricing');

		// Update Status
		Route::post('/durum-guncelle/{id}/{status}', 'DevelopmentController@updateStatus')->name('update.status');
	});

	/*
	 |--------------------------------------------------------------------------
	 |  Research | Error(Bug) Reports Group
	 |--------------------------------------------------------------------------
	*/
	Route::any('errors/data', 'ErrorController@data')->name('errors.data');
	Route::any('errors/file/destroy/{file}', 'ErrorController@fileDestroy')->name('errors.file.destroy');
	Route::put('errors/priority/update/{id}', 'ErrorController@updatePriority')->name('errors.priority.update');
	Route::put('errors/status/update/{id}', 'ErrorController@updateStatus')->name('errors.status.update');
	Route::post('errors/reply/{id}', 'ErrorController@reply')->name('errors.reply');
	Route::get('errors/edit/reply/{id}', 'ErrorController@replyEdit')->name('errors.replyEdit');
	Route::put('errors/update/reply/{id}', 'ErrorController@replyUpdate')->name('errors.replyUpdate');
	Route::delete('errors/destroy/reply/{id}', 'ErrorController@replyDestroy')->name('errors.replyDestroy');
	Route::resource('errors', 'ErrorController');
});

Entities/Development.php
<?php

namespace Penta\ResearchDevelopment\Entities;

use App\Admin;
use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Schema;
use Penta\ResearchDevelopment\Helper\StatusInterface;
use Penta\ResearchDevelopment\Helper\StatusTrait;

class Development extends Model implements StatusInterface
{
	use StatusTrait;

	const STATUS_PENDING_PRICING = 'pending_pricing';

	const STATUS_PRICING         = 'pricing';

	protected $fillable = [
		'description',
		'row',
		'title',
		'section',
		'price',
		'price_desc',
		'status',
		'user_id',
	];

	public function user()
	{
		if (Schema::hasTable('admins') && class_exists(Admin::class)) {
			return $this->hasOne(Admin::class, 'id', 'user_id');
		} else {
			return $this->hasOne(User::class, 'id', 'user_id');
		}
	}

	public function getStatusWithHtml()
	{
		switch ($this->attributes['status']) {
			case self::STATUS_PENDING_APPROVED:
				return $this->htmlButton('warning', 'Onay Bekliyor');
			case self::STATUS_APPROVED:
				return $this->htmlButton('primary', 'Onaylandı');
			case self::STATUS_UNAPPROVED:
				return $this->htmlButton('danger', 'Onaylanmadı');
			case self::STATUS_IN_PROCESS:
				return $this->htmlButton('blue-grey', 'İşlemde');
			case self::STATUS_SOLVED:
				return $this->htmlButton('success', 'Tamamlandı');
			case self::STATUS_UNSOLVED:
				return $this->htmlButton('pink', 'Yapılmadı');
			case self::STATUS_PENDING_PRICING:
				return $this->htmlButton('facebook', 'Fiyatlandırma Bekleniyor');
			case self::STATUS_PRICING:
				return $this->htmlButton('google', 'Fiyatlandırıldı').
					" <button data-toggle='tooltip' title='Fiyatı Gör' class='btn btn-sm no-action cursor-pointer btn-primary show_price' href='".
					route('arge.development.showPricing', $this->id)."'><i class='fa fa-eye'></i></button>";
			default:
				return $this->htmlButton('blue', 'Tanımsız');
		}
	}
}

Http/Controllers/DevelopmentController.php
<?php

namespace Penta\ResearchDevelopment\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Mail;
use Penta\ResearchDevelopment\Entities\Development;
use Penta\ResearchDevelopment\Mail\DevelopmentMail;
use Yajra\DataTables\DataTables;

class DevelopmentController extends Controller
{
	use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('researchdevelopment::development.index');
	}

	/**
	 * @return mixed
	 * @throws \Exception
	 */
	public function data()
	{

		$developmentNotes = Development::query()->orderByRaw('case when status = \'pending_approved\' then 1
	              when status = \'approved\' then 2
	              when status = \'in_process\' then 3
	              when status = \'unsolved\' then 4
	              when status = \'unapproved\' then 5
	              else 6
	            end asc')->with('user');

		return DataTables::of($developmentNotes)->addColumn('action', function ($development) {
			return view('researchdevelopment::development.action', compact('development'));
		})->editColumn('status', function ($development) {
			return $development->getStatusWithHtml();
		})->filterColumn('status', function ($query, $keyword) {
			$sql = "IF(status = ?,'Onay Bekliyor',";
			$sql .= "IF(status = ?,'Onaylandı',";
			$sql .= "IF(status = ?,'Onaylanmadı',";
			$sql .= "IF(status = ?,'İşlemde',";
			$sql .= "IF(status = ?,'Tamamlandı',";
			$sql .= "IF(status = ?,'Fiyatlandırma Bekleniyor',";
			$sql .= "IF(status = ?,'Fiyatlandırıldı',";
			$sql .= "IF(status = ?,'Yapılmadı','')))))))) like ?";

			$query->whereRaw($sql, [
				Development::STATUS_PENDING_APPROVED,
				Development::STATUS_APPROVED,
				Development::STATUS_UNAPPROVED,
				Development::STATUS_IN_PROCESS,
				Development::STATUS_SOLVED,
				Development::STATUS_PENDING_PRICING,
				Development::STATUS_PRICING,
				Development::STATUS_UNSOLVED,
				'%'.$keyword.'%',
			]);
		})->editColumn('created_at', function ($development) {
			return $development->created_at->diffForHumans();
		})->rawColumns(['status', 'action'])->make(true);
	}

	/**
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function store(Request $request)
	{
		$this->validate($request, [
			'title'       => 'required|max:191',
			'description' => 'required',
		], [
			'title.required'       => 'Lütfen bir başlık giriniz.',
			'title.max'            => 'Başlık alanı maksimum 191 karakter olabilir. Karakter sayısı '.strlen($request->get('title')),
			'description.required' => 'Lütfen bir açıklama belirtiniz.',
		]);

		$attributes = $request->all();
		$attributes['user_id'] = auth()->id();

		$create = Development::create($attributes);

		Mail::to(config('researchdevelopment.mails', []))->send(new DevelopmentMail($create));

		return back()->with('toastr_success', 'Geliştirme Talebi Oluşturuldu');
	}

	/**
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\JsonResponse
	 */
	public function show(Request $request)
	{
		if ($request->ajax()) {
			$id = (int)$request->get('id');

			$development = Development::findOrFail($id);

			return response()->json(['success' => true, 'description' => $development->description, 'title' => $development->title]);
		}

		abort(404);
	}

	/**
	 * @param \Penta\ResearchDevelopment\Entities\Development $development
	 *
	 * @return \Illuminate\Http\JsonResponse
	 */
	public function edit(Development $development)
	{
		if ( ! \request()->ajax()) {
			abort(404);
		}

		$attributes = $development->toArray();
		$attributes['action'] = route('researchdevelopment.developments.updateEdit', $development);

		return response()->json($attributes);
	}

	/**
	 * @param \Illuminate\Http\Request $request
	 * @param \Penta\ResearchDevelopment\Entities\Development $development
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 * @throws \Illuminate\Validation\ValidationException
	 */
	public function updateEdit(Request $request, Development $development)
	{
		$this->validateWithBag('edit', $request, [
			'title'            => 'required|max:191',
			'edit_description' => 'required',
			'row'              => 'nullable|integer',
			'section'          => 'required',
		], [
			'title.required'            => 'Lütfen bir başlık giriniz.',
			'title.max'                 => 'Başlık alanı maksimum 191 karakter olabilir. Karakter sayısı '.strlen($request->get('title')),
			'edit_description.required' => 'Lütfen bir açıklama belirtiniz.',
			'section.required'          => 'Lütfen bir bölüm belirtiniz.',
			'row.integer'               => 'Sıra numarası sadece sayısal değer olabilir.',
		]);

		$attributes = $request->except('action');
		$attributes['row'] = empty($request->get('row')) ? '999' : $request->get('row');
		$attributes['description'] = $request->get('edit_description');

		$update = $development->update($attributes);
		if ($update) {

			return back()->with('toastr_success', 'Geliştirme notu güncellendi.');
		}

		return back()->with('toastr_error', 'Geliştirme notu güncellenemedi');
	}

	/**
	 * @param $id
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function destroy($id)
	{
		Development::destroy($id);

		return response()->json(['messsage' => 'Deleted']);
	}

	/**
	 * @param $id
	 *
	 * @return \Illuminate\Http\JsonResponse
	 */
	public function showPricing($id)
	{
		$development = Development::findOrFail($id);

		return response()->json([
			'success'     => true,
			'development' => $development,
		]);
	}

	/**
	 * @param \Illuminate\Http\Request $request
	 *
	 * @param $id
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 * @throws \Illuminate\Validation\ValidationException
	 */
	public function updatePricing(Request $request, $id)
	{
		$this->validateWithBag('price', $request, ['price' => 'required']);

		Development::findOrFail($id)->update([
			'price'      => $request->get('price'),
			'status'     => Development::STATUS_PRICING,
			'price_desc' => $request->get('price_desc'),
		]);

		return back()->with('toastr_success', 'Fiyatlandırma Uygulandı');
	}

	/**
	 * @param $id
	 * @param $status
	 *
	 * @return \Illuminate\Http\JsonResponse
	 */
	public function updateStatus($id, $status)
	{
		$development = Development::findOrFail($id);

		$attributes = ['status' => $status];

		$development->update($attributes);

		if ($status === Development::STATUS_APPROVED) {
			Mail::to(config('oguslarkia.mails'))->send(new ApprovedMail($development));
		}

		return response()->json(['message' => 'Updated']);
	}
}

Resources/views/development/action.blade.php
@component('researchdevelopment::components.action')
    @role(config('researchdevelopment.roles.couple'))
    @slot('edit')
        <a data-url="{{ route('researchdevelopment.developments.edit',$development->id) }}"
           class="dropdown-item edit_development">
            <i class="fa fa-edit"></i>
            Düzenle
        </a>
    @endslot

    @slot('show')
        <a data-id="{{ $development->id }}"
           class="dropdown-item view_development">
            <i class="fa fa-eye"></i>
            İncele
        </a>
    @endslot

    @slot('delete')
        <a data-action="{{ route('researchdevelopment.developments.destroy',$development->id) }}"
           class="dropdown-item __delete__researchdevelopment">
            <i class="ft-trash"></i>
            Sil
        </a>
    @endslot
    @endrole

    @if($development->status == $development::STATUS_PRICING && optional(auth()->user())->hasRole(config('researchdevelopment.roles.owner')))
        <div class="dropdown-divider"></div>
        <a href="{{ route('researchdevelopment.developments.update.status',['status' => $development::STATUS_APPROVED,'id' => $development->id]) }}"
           class="update_publish_state dropdown-item">
            <i class="fa fa-calendar-check-o success"></i>
            Onayla
        </a>
        <a href="{{ route('researchdevelopment.developments.update.status',['status' => $development::STATUS_UNAPPROVED,'id' => $development->id]) }}"
           class="dropdown-item update_publish_state">
            <i class="fa fa-calendar-times-o amber"></i>
            Onaylama
        </a>
    @endif

    @role(config('researchdevelopment.roles.developer'))

    @if($development->status == $development::STATUS_APPROVED || $development->status == $development::STATUS_IN_PROCESS)
        <div class="dropdown-divider"></div>
        @if($development->status == $development::STATUS_IN_PROCESS)
            <a href="{{ route('researchdevelopment.developments.update.status',['status' => $development::STATUS_SOLVED,'id' => $development->id]) }}"
               class="dropdown-item update_publish_state">
                <i class="fa fa-check-circle-o primary"></i>
                Tamamlandı Olarak İşaretle
            </a>
            <a href="{{ route('researchdevelopment.developments.update.status',['status' => $development::STATUS_UNSOLVED,'id' => $development->id]) }}"
               class="dropdown-item update_publish_state">
                <i class="fa fa-times-circle-o danger"></i>
                Yapılmadı Olarak İşaretle
            </a>
        @else
            <a href="{{ route('researchdevelopment.developments.update.status',['status' => $development::STATUS_IN_PROCESS,'id' => $development->id]) }}"
               class="dropdown-item update_publish_state">
                <i class="fa fa-spinner blue"></i>
                İşlemde Olarak İşaretle
            </a>
        @endif
    @else
        <div class="dropdown-divider"></div>
        <a data-url="{{ route('researchdevelopment.developments.updatePricing',$development->id) }}"
           class="dropdown-item pricing">
            <i class="fa fa-try google"></i>
            Fiyatlandır
        </a>
    @endif
    @endrole

@endcomponent

Resources/views/development/create.blade.php
<div class="modal fade text-left" id="new_note" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel1">Yeni Geliştirme Talebi</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {!! BootForm::open()->action(route('researchdevelopment.developments.store'))->class('form') !!}
            <div class="modal-body">
                {!! BootForm::text('Başlık', 'title')->required() !!}
                {!! BootForm::textarea('Açıklama', 'description')->id('researchdevelopment')->rows(50) !!}
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-outline-primary" value="Kaydet">
            </div>
            {!! BootForm::close() !!}
        </div>
    </div>
</div>

Resources/views/development/edit.blade.php
<div class="modal fade text-left" id="edit_development" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            @if(count($errors->edit->all()) > 0)
                <ul class="alert alert-danger alert-dismissible mb-2 list-unstyled" role="alert">
                    @foreach($errors->edit->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel1">Geliştirme Talebi Düzenle</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {!! BootForm::open()->class('form')->enctype('multipart/form-data')->put() !!}
            {!! BootForm::hidden('action')->class('action_class')  !!}
            <div class="modal-body">
                {!! BootForm::text('Başlık', 'title')->required() !!}
                {!! BootForm::textarea('Açıklama', 'edit_description')->required()->id('researchdevelopment_edit')->rows(50) !!}
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-outline-primary edit_submit_btn" value="Kaydet">
            </div>
            {!! BootForm::close() !!}
        </div>
    </div>
</div>

Resources/views/development/index.blade.php
@extends(config('researchdevelopment.view.extends'))

@section(config('researchdevelopment.view.body'))

    @component('researchdevelopment::components.content')

        @slot('head')
            Geliştirme Talebi
        @endslot

        @slot('buttons')
            <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#new_note">
                <i class="fa fa-plus-circle"></i>
                Yeni Not Ekle
            </button>
            @include('researchdevelopment::development.create')
            @include('researchdevelopment::development.edit')
            @include('researchdevelopment::development.show')
            @include('researchdevelopment::development.pricing')
            @include('researchdevelopment::development.showPrice')
        @endslot

        @slot('body')
            @component('researchdevelopment::components.table', ['url' => route('researchdevelopment.developments.data')])
                <tr>
                    <th data-data="title">Başlık</th>
                    <th data-data="status">Durum</th>
                    <th data-data="user.full_name" data-orderable="false" data-searchable="false">Oluşturan</th>
                    <th data-data="created_at">Oluşturma Tarih</th>
                    <th data-data="action" data-orderable="false" data-searchable="false" width="1%">Ayarlar</th>
                </tr>
            @endcomponent
        @endslot
    @endcomponent

@endsection

@section(config('researchdevelopment.view.css'))
    @include('researchdevelopment::assets.css.table')
    @include('researchdevelopment::assets.css.toastr')
@endsection

@section(config('researchdevelopment.view.js'))
    @include('researchdevelopment::assets.js.table')
    @include('researchdevelopment::assets.js.toastr')
    @include('researchdevelopment::inc.toastr')

    <script src="{{ asset('vendor/researchdevelopment/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ asset('vendor/researchdevelopment/tinymce/langs/tr_TR.js') }}"></script>
    <script src="{{ asset('vendor/researchdevelopment/global/global.js') }}"></script>
    <script>
        var editor_config = {
            selector: 'textarea#researchdevelopment',
            branding: false,
            menubar: false,
            toolbar: 'undo redo | styleselect | bold italic | link'
        };
    </script>
    <script>
        $(function () {
            tinymce.init(editor_config);
        });
    </script>

    <script>
        $(function () {
            $('body').on('shown.bs.modal', '#edit_development', function () {
                $('#edit_development form').attr('action', $('.action_class').val());
            });
            $('body').on('shown.bs.modal', '#pricing', function () {
                $('#pricing form').attr('action', $('.pricing_action_class').val());
                $('#pricing form').attr('action', $('.pricing_action_class').val());
            });

            // show error note
            function showDevelopment(data) {
                var url = '{{ route('researchdevelopment.developments.show') }}';
                $.post(url, data, function (resp) {

                    if (resp.success) {

                        $('#show_note').find('.description').html(resp.description);
                        $('#show_note').find('.id').html(resp.id);
                        $('#show_note').find('.title').html(resp.title);
                        if (resp.image != null) {
                            $('#show_note').find('.image_text').html('Resim');
                            $('#show_note').find('.image').html("<a target='_blank' href='" + resp.image + "'><img  src='" + resp.image + "' width='566'/></a>");
                        } else {
                            $('#show_note').find('.image_text').html('');
                            $('#show_note').find('.image').html('');
                        }

                        $('#show_note').modal('show');
                    }

                }).fail(function (resp) {
                    toastr.error(resp.responseText, "Hata !");
                }).done(function (resp) {
                });
            }

            // review development data
            $('body').on('click', '.view_development', function () {

                var id = $(this).data('id');
                var data = {
                    _token: '{{ csrf_token() }}',
                    id: id
                };

                showDevelopment(data);

            });

            // on click development edit button
            $('body').on('click', '.edit_development', function (e) {
                e.preventDefault();
                var url = $(this).data('url');

                var $form = $('#edit_development').find('form');
                $.get(url, function (resp) {
                    $form.find('.action_class').val(resp.action);
                    $form.find('#title').val(resp.title);
                    $form.find('#row').val(resp.row);
                    $form.find('textarea#researchdevelopment_edit').val(resp.description);

                    editor_config.selector = 'textarea#researchdevelopment_edit';

                    tinymce.init(editor_config);

                    $('#edit_development').modal('show');

                }).fail(function () {
                    toastr.error("Sunucuya ulaşılamıyor.");
                });

            });


            // on click pricing button
            $('body').on('click', '.pricing', function (e) {
                e.preventDefault();
                var url = $(this).data('url');
                $('#pricing .pricing_action_class').val(url);
                $('#pricing').modal('show');
            });

            $('body').on('click', '.show_price', function (e) {
                e.preventDefault();
                var href = $(this).attr('href');
                $.get(href, function (response) {
                    $('#showPricing #price').val(response.development.price + ' ₺');
                    $('#showPricing #desc').html(response.development.price_desc);
                    $('#showPricing').modal('show');
                }).fail((error) => {

                    if (error.status === 403) {
                        toastr.warning('Bu işleme yetkiniz yok', 'İzin Yok', {
                            positionClass: "toast-bottom-right"
                        });
                    } else {
                        toastr.error('Beklenmeyen bir hata oluştu ! Tekrar deneyin...', '', {
                            positionClass: "toast-bottom-right"
                        })
                    }
                });
            });
        });
    </script>
    @if($errors->all())
        <script>
            $(function () {
                $('#new_note').modal('show');

            });
        </script>
    @elseif($errors->edit->all())
        <script>
            $(function () {
                $('#edit_development').modal('show');
            });
        </script>
    @elseif($errors->price->all())
        <script>
            $(function () {
                $('#pricing').modal('show');
            });
        </script>
    @endif
    <script src="{{ asset('vendor/researchdevelopment/tables/table.js') }}"></script>

@endsection

Resources/views/development/pricing.blade.php
<div class="modal fade text-left" id="pricing" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel1">Fiyatlandırma</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {!! BootForm::open()->action('')->class('form')->put() !!}
            {!! BootForm::hidden('pricing_action')->class('pricing_action_class')  !!}
            <div class="modal-body">
                {!! BootForm::text('Fiyat', 'price')->required()->type('number') !!}
                @if($errors->price->has('price'))
                    <p class="help-block danger">
                        {{ $errors->price->first('price') }}
                    </p>
                @endif
                {!! BootForm::textarea('Açıklama', 'price_desc') !!}
                @if($errors->has('price_desc'))
                    <p class="help-block danger">
                        {{ $errors->first('price_desc') }}
                    </p>
                @endif
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-outline-primary" value="Kaydet">
            </div>
            {!! BootForm::close() !!}
        </div>
    </div>
</div>

Resources/views/development/show.blade.php
<!-- Modal: modalPoll -->
<div class="modal fade right" id="show_note" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-full-height modal-right modal-notify modal-info" role="document">
        <div class="modal-content">
            <!--Header-->
            <div class="modal-header">
                <span>#</span>
                <span class="id font-weight-bold">1</span>
                <span class="">-</span>
                <span class="title font-weight-bold"></span>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="white-text">×</span>
                </button>
            </div>

            <!--Body-->
            <div class="modal-body">
                <div class="text-center">
                    <p><strong>Açıklama</strong></p>
                    <p class="description"></p>
                </div>
            </div>

            <!--Footer-->
            <div class="modal-footer justify-content-center">
                <button class="btn btn-outline-secondary cursor-pointer" data-dismiss="modal">Kapat</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal: modalPoll -->

Resources/views/development/showPrice.blade.php
<div class="modal fade text-left" id="showPricing" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel1">Fiyatlandırma</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                	<label class="control-label" for="price">Fiyat</label>
                    <input type="text"  id="price" disabled readonly class="form-control">
                </div>
                <div class="form-group">
                	<label class="control-label" for="desc">Açıklama</label>
                    <div readonly disabled class="form-control" id="desc">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>